//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelReservationSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public string username { get; set; }
        public Nullable<int> typID { get; set; }
        public string email { get; set; }
        public string pasword { get; set; }
        public string phone { get; set; }
        public string addrss { get; set; }
    
        public virtual userType userType { get; set; }
    }
}
